version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.40
    environment:
      MYSQL_DATABASE: ssafy_log
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # 데이터 저장을 위한 volume 설정
    networks:
      - my_network

networks:
  my_network:
    external: true

volumes:
  mysql_data: # named volume 정의
